//
//  CourseDetailsModels.swift
//  SwiftBookApp
//
//  Created by Alexey Turulin on 10/2/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

typealias CourseDetailsRequest = CourseDetails.ShowCourseDetails.Request
typealias CourseDetailsResponse = CourseDetails.ShowCourseDetails.Response
typealias CourseDetailsViewModel = CourseDetails.ShowCourseDetails.ViewModel

enum CourseDetails {
 
    // MARK: Use cases
    enum ShowCourseDetails {
        struct Request {
            let course: Course
        }
        
        struct Response {
            let courseName: String
        }
        
        struct ViewModel {
            let courseName: String
        }
    }
}
