//
//  CourseDetailsWorker.swift
//  SwiftBookApp
//
//  Created by Alexey Turulin on 10/2/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

class CourseDetailsWorker {
    func getImageData(from url: URL?) -> Data? {
        NetworkManager.shared.fetchImageData(from: url)
    }
    
    func getFavoriteStatus(for courseName: String) -> Bool {
        DataManager.shared.getFavoriteStatus(for: courseName)
    }
    
    func setFavoriteStatus(for courseName: String, with status: Bool) {
        DataManager.shared.setFavoriteStatus(for: courseName, with: status)
    }
}
