//
//  CourseDetailsInteractor.swift
//  SwiftBookApp
//
//  Created by Alexey Turulin on 10/2/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol CourseDetailsBusinessLogic {
    func provideCourseDetails(for course: Course)
}

protocol CourseDetailsDataStore {
    
}

class CourseDetailsInteractor: CourseDetailsBusinessLogic, CourseDetailsDataStore {
    var presenter: CourseDetailsPresentationLogic?
    var worker: CourseDetailsWorker?
    
    func provideCourseDetails(for course: Course) {
        worker = CourseDetailsWorker()
        worker?.doSomeWork()
        
        let response = CourseDetailsResponse(courseName: course.name)
        presenter?.presentCourseDetails(response: response)
    }
}
